name: feedstand

services:
  frontend:
    image: feedstand/frontend:test
    build:
      context: ..
      dockerfile: apps/frontend/.docker/Dockerfile.test

  backend:
    image: feedstand/backend:test
    build:
      context: ..
      dockerfile: apps/backend/.docker/Dockerfile.test
